#!/bin/bash

if [ -z $1 ] ; then
  echo "Type (devnet/chainlink) parameter needed!" && exit 1;
fi

imageid=`docker images -f "reference=smartcontract/$1:latest" | tail -n1 | awk '{ print $3; }'`
dirtydigest=`docker inspect --format='{{.RepoDigests}}' $imageid`
echo $dirtydigest | sed 's/^\[\(.*\)\]$/\1/'
