#!/bin/bash
# Taken from https://devcenter.heroku.com/articles/ssl-certificate-self

cd `dirname $0`
mkdir -p tmp
cd tmp

read -p 'Please enter the domain or hit enter for blank (e.g. www.example.com): ' DOMAIN
if [ -z "$DOMAIN" ]; then
  DOMAIN=chainlink.dev
fi

openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key \
  -out server.crt -subj "/OU=chainlink.development/CN=$DOMAIN/O=$DOMAIN"

echo
echo "Files are in tmp/"
